package pruss

const (
	PRU0_PRU1_INTERRUPT = 32
	PRU1_PRU0_INTERRUPT = 33
	PRU0_ARM_INTERRUPT  = 34
	PRU1_ARM_INTERRUPT  = 35
	ARM_PRU0_INTERRUPT  = 36
	ARM_PRU1_INTERRUPT  = 37

	CHANNEL0 = 0
	CHANNEL1 = 1
	CHANNEL2 = 2
	CHANNEL3 = 3
	CHANNEL4 = 4
	CHANNEL5 = 5
	CHANNEL6 = 6
	CHANNEL7 = 7
	CHANNEL8 = 8
	CHANNEL9 = 9

	PRU0        = 0
	PRU1        = 1
	PRU_EVTOUT0 = 2
	PRU_EVTOUT1 = 3
	PRU_EVTOUT2 = 4
	PRU_EVTOUT3 = 5
	PRU_EVTOUT4 = 6
	PRU_EVTOUT5 = 7
	PRU_EVTOUT6 = 8
	PRU_EVTOUT7 = 9
)

type PruIntcInitData struct {
	SysevtsEnabled     []uint8
	SysevtToChannelMap SysevtToChannelMap
	ChannelToHostMap   ChannelToHostMap
	HostEnabled        []uint8
}

var DefaultInitData = PruIntcInitData{
	SysevtsEnabled: []uint8{
		PRU0_PRU1_INTERRUPT,
		PRU1_PRU0_INTERRUPT,
		PRU0_ARM_INTERRUPT,
		PRU1_ARM_INTERRUPT,
		ARM_PRU0_INTERRUPT,
		ARM_PRU1_INTERRUPT,
	},
	SysevtToChannelMap: SysevtToChannelMap{
		PRU0_PRU1_INTERRUPT: CHANNEL1,
		PRU1_PRU0_INTERRUPT: CHANNEL0,
		PRU0_ARM_INTERRUPT:  CHANNEL2,
		PRU1_ARM_INTERRUPT:  CHANNEL3,
		ARM_PRU0_INTERRUPT:  CHANNEL0,
		ARM_PRU1_INTERRUPT:  CHANNEL1,
	},
	ChannelToHostMap: ChannelToHostMap{
		CHANNEL0: PRU0,
		CHANNEL1: PRU1,
		CHANNEL2: PRU_EVTOUT0,
		CHANNEL3: PRU_EVTOUT1,
	},
	HostEnabled: []uint8{
		PRU0,
		PRU1,
		PRU_EVTOUT0,
		PRU_EVTOUT1,
	},
}
